FIND_PATH(GCD_INCLUDE_DIR NAMES dispatch/dispatch.h)
MARK_AS_ADVANCED(GCD_INCLUDE_DIR)
 
FIND_LIBRARY(GCD_LIBRARY NAMES
dispatch
libdispatch
dispatchlib
)
MARK_AS_ADVANCED(GCD_LIBRARY)
 
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS (GCD DEFAULT_MSG
                                   GCD_LIBRARY GCD_INCLUDE_DIR)
