FIND_PATH(VN3D_INCLUDE_DIR NAMES vn3d/vn3d.h)
MARK_AS_ADVANCED(VN3D_INCLUDE_DIR)
 
FIND_LIBRARY(VN3D_LIBRARY NAMES
vn3d
libvn3d
)
MARK_AS_ADVANCED(VN3D_LIBRARY)
 
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(VN3D DEFAULT_MSG VN3D_LIBRARY VN3D_INCLUDE_DIR)
